### ISSUE TITLE
can i get trainning code? 

### ISSUE THREAD

**Issue by m4a1carbin4** [luosiallen/latent-consistency-model#10]
it's realy very, very surprising results. 
(enough to make me look back at myself for giving up on graduate school.)

I hope you guys get good reviews on this paper.

I'm curious is there any script provision plan for model training? If possible, for the Lora script too.

**Comment by luosiallen** [comment]
Training codes will be released, after we distill some ongoing models.

**Comment by peki12345** [comment]
> Training codes will be released, after we distill some ongoing models.

Hi, luosiallen. Do you have any plans to distill the inpainting model, like sd1.5-inpaint?

**Comment by luosiallen** [comment]
Using the img2img method, i think it can somehow to perform inpainting.
