### ISSUE TITLE
Question : where's the model downloaded to ?

### ISSUE THREAD

**Issue by x4080** [luosiallen/latent-consistency-model#12]
Hi, I tested it in mac and it automatically download the model, where's the file location ? Thanks

**Comment by luosiallen** [comment]
The default download path should be: /Volumes/Macintosh HD/Users/username/.cache/huggingface/hub/models--SimianLuo--LCM_Dreamshaper_v7

**Comment by x4080** [comment]
@luosiallen Thanks

**Comment by x4080** [comment]
@luosiallen BTW it can run very fast also in my m2 pro 16gb. One of the coolest project this year !

**Comment by luosiallen** [comment]
Thanks for enjoying it!
