### ISSUE TITLE
training code and more models

### ISSUE THREAD

**Issue by LJ-Zhang** [luosiallen/latent-consistency-model#13]
1. would you release the training code, e.g. finetuning on custom datasets? 
2. Will more pretrained models be released in the future, e.g. distilled version of official SD-v1.5?

**Comment by luosiallen** [comment]
For sure. We have some ongoing models to distill.

**Comment by Amin456789** [comment]
it will be great if u add lyriel 1.6 too!

**Comment by luosiallen** [comment]
I will take a look.

**Comment by Amin456789** [comment]
thank u!
