### ISSUE TITLE
error AttributeError: module diffusers has no attribute LCMScheduler.

### ISSUE THREAD

**Issue by gaodianzhuo** [luosiallen/latent-consistency-model#19]
报错了,能否提供diffusers使用的版本?
AttributeError: module diffusers has no attribute LCMScheduler

**Comment by luosiallen** [comment]
try this: 
`pipe = DiffusionPipeline.from_pretrained("SimianLuo/LCM_Dreamshaper_v7", custom_pipeline="latent_consistency_txt2img", custom_revision="main", revision="fb9c5d")`

**Comment by luosiallen** [comment]
Try this:
`pipe = DiffusionPipeline.from_pretrained("SimianLuo/LCM_Dreamshaper_v7", custom_pipeline="latent_consistency_txt2img", custom_revision="main", revision="fb9c5d")`
