### ISSUE TITLE
Document : Adding Contribution section to the Readme.md file.

### ISSUE THREAD

**Issue by Kalyanimhala** [luosiallen/latent-consistency-model#21]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The "Contributors" section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/luosiallen/latent-consistency-model/assets/147402107/96d70181-bdc7-45ee-854e-c4359d3023b3)

**Comment by Kalyanimhala** [comment]
@luosiallen  Kindly assign me this issue, I want to work on it. Thank You!!

**Comment by luosiallen** [comment]
Thanks for the suggestion. Just raise a PR, i will merge it.
