### ISSUE TITLE
About pred x0 model 

### ISSUE THREAD

**Issue by Costwen** [luosiallen/latent-consistency-model#24]
I noticed that you have open-sourced the related models and code for LCM on HuggingFace, which is very useful to me.
However, I found that the existing models use either pred_eps or pred_v.
I want to ask if you have conducted experiments with the pred_x0 mode, and do you have the corresponding checkpoint files? If so, could you provide some relevant information or resources? Thank you very much for your help and support!

**Comment by luosiallen** [comment]
as far as i know, no SD model is using pred_x0 as prediction target.
