### ISSUE TITLE
Stable Diffusion-V2.1-Base model

### ISSUE THREAD

**Issue by Luciennnnnnn** [luosiallen/latent-consistency-model#27]
Hi, great work! The paper stated that latent consistency model is distillated from Stable Diffusion-V2.1-Base, however, this repo only provide Dreamshaper v7 model, a version of Stable-Diffusion v1-5. Why it is the case? Does Dreamshaper v7 better than Stable Diffusion-V2.1-Base?

**Comment by luosiallen** [comment]
We will release these following checkpoints one by one,  be patient. This Dreamshaper v7 distilled model is for demonstration.
