### ISSUE TITLE
is there a normal sd version of this model?

### ISSUE THREAD

**Issue by Amin456789** [luosiallen/latent-consistency-model#28]
Hi!

after using this model i totally fell in love with it, it is so beautiful, i checked the normal dreamshaper v7 but it was totally different

do u guys have this model as a normal 1.5 model as well to use with euler or ddim?

kind regards

**Comment by bonlime** [comment]
@Amin456789 LCM can't work with samplers like ddim/euler, it's too different from vanilla SD
