### ISSUE TITLE
How get_scalings_for_boundary_condition_discrete is defined

### ISSUE THREAD

**Issue by Luciennnnnnn** [luosiallen/latent-consistency-model#29]
Hi, I notice that you define `get_scalings_for_boundary_condition_discrete()` different from [original consistency model](https://github.com/huggingface/diffusers/blob/9ced7844daffc1877b0c599a318371cfe09108f5/src/diffusers/schedulers/scheduling_consistency_models.py#L254C30-L254C30), how do you derive your formulation?

**Comment by luosiallen** [comment]
Simply just a impulse function.
