### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by howardgriffin** [luosiallen/latent-consistency-model#3]
Hi, when will the code be released? Thank you!

**Comment by luosiallen** [comment]
We will release our generation demos (Hugging Face Inference API), and pretrained model in two weeks. Thanks for asking !

**Comment by Ryu1845** [comment]
Is there any plan to release the training code?

**Comment by anotherjesse** [comment]
Love this project!  Great work!

I second the request for training code - as the current model can be fairly NSFW (and doesn't support negative prompts to steer away from that content)  I'm wondering if creating a version of LCM against a different checkpoint would help with SFW

**Comment by luosiallen** [comment]
Training codes will be released, after we distill some onging SD models. We will figure out a way how to add negative prompts into LCM. Welcome to join the discord for further discussion.
