### ISSUE TITLE
issue with [Combine LCM LoRAs with regular SDXL LoRAs]

### ISSUE THREAD

**Issue by Roveer** [luosiallen/latent-consistency-model#41]
Hi! I have followed your blog [SDXL in 4 steps with Latent Consistency LoRAs](https://huggingface.co/blog/lcm_lora)  to inference. But when I going to [Combine LCM LoRAs with regular SDXL LoRAs](https://huggingface.co/blog/lcm_lora#bonus-combine-lcm-loras-with-regular-sdxl-loras), the quality of the images I got  is not as high as your blog. Then I copied your code and re-inferenced, but the quality of the images is still very low. And I don't know why. 
Is it possible that there is an issue with the diffusers version?

**Comment by luosiallen** [comment]
update to diffusers=0.23.0 first.

**Comment by Roveer** [comment]
Yes, I'm using version 0.23.0, but the resulting image is still blurry. And the parameters are all the same as yours. But this happens only in the case [Combine LCM LoRAs with regular SDXL LoRAs](https://huggingface.co/blog/lcm_lora#bonus-combine-lcm-loras-with-regular-sdxl-loras).
![image_test](https://github.com/luosiallen/latent-consistency-model/assets/75512406/452633bb-7332-4119-bdf7-66e8c7bdbd29)
just like this.

**Comment by PeiqinSun** [comment]
I also found this problem. Any solution?

**Comment by ChenFangDart** [comment]
hello, I am having this issue as well. Any help is appreciated!

**Comment by luosiallen** [comment]
will check later. Have you guys install peft library?

```
!pip install -q transformers accelerate
!pip install peft
!pip install diffusers
```

**Comment by luosiallen** [comment]
make sure this is correct first: https://huggingface.co/docs/diffusers/main/en/tutorials/using_peft_for_inference

**Comment by patil-suraj** [comment]
Could you please post a code snippet ?

**Comment by Roveer** [comment]
Hello, I found some problems in this blog, when the function "pipe.load_lora_weights" loads LoRA, the parameter "adapter_name" is not specified as "lora".
The original code:
 `pipe.load_lora_weights(lcm_lora_id)`
Just code it to:
`pipe.load_lora_weights(lcm_lora_id, adapter_name="lora")`
and then you got a satisfying image.
