### ISSUE TITLE
timestep_cond is need?

### ISSUE THREAD

**Issue by qiuyang163** [luosiallen/latent-consistency-model#45]
<img width="867" alt="image" src="https://github.com/luosiallen/latent-consistency-model/assets/8520472/195f34b7-2a6f-406c-b212-270fe528bd79">
Does teacher model must have timestep_cond in lcm distilling? My pretrain model is sd1.5 and it is don't have this weight.
When I remove timestep_cond code, the distilled model result is strange like this
<img width="465" alt="image" src="https://github.com/luosiallen/latent-consistency-model/assets/8520472/218dc48e-cd6c-48d2-9c9f-c9da40aaff62">
</br>
I use one A100 to train about 35400 step, and loss is desending normally.
<img width="428" alt="image" src="https://github.com/luosiallen/latent-consistency-model/assets/8520472/2d302d71-2fe0-46fd-9b9a-baae8e23587e">

@luosiallen

**Comment by luosiallen** [comment]
initalize these parameter randomly.

**Comment by ZNan-Chen** [comment]
@qiuyang163 I have the same problem, have you solved it?
