### ISSUE TITLE
v_prediction error

### ISSUE THREAD

**Issue by dcfucheng** [luosiallen/latent-consistency-model#53]
In the "predicted_origin" method in train.py, prediction_type == "epsilon" can work well, but prediction_type == "v_prediction" will meet this error.

*** RuntimeError: The size of tensor a (10) must match the size of tensor b (64) at non-singleton dimension 3

Should the "sigmas" and "alphas" in prediction_type == "v_prediction"  are also processed by extract_into_tensor() for matching shapes as in prediction_type == "epsilon"?

Like this
```
    if prediction_type == "epsilon":
        sigmas = extract_into_tensor(sigmas, timesteps, sample.shape)
        alphas = extract_into_tensor(alphas, timesteps, sample.shape)
        pred_x_0 = (sample - sigmas * model_output) / alphas
    elif prediction_type == "v_prediction":
        sigmas = extract_into_tensor(sigmas, timesteps, sample.shape)
        alphas = extract_into_tensor(alphas, timesteps, sample.shape)
        pred_x_0 = alphas * sample - sigmas * model_output
    else:
        raise ValueError(f"Prediction type {prediction_type} currently not supported.")
```
Am I right？Thanks~

**Comment by luosiallen** [comment]
just fixed it.
