### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by TonyLianLong** [luosiallen/latent-consistency-model#55]
The training code involves using `muse-dataset` bucket from s3. However, it seems that the dataset is not publicly accessible. Is it possible to make the s3 bucket public for reproduction? This seems to be a processed version of LAION-A6+, which is different from LAION-A6+ on [huggingface](https://huggingface.co/datasets/ChristophSchuhmann/improved_aesthetics_6plus/tree/main/data).

The dataset path in the command:
```
s3://muse-datasets/laion-aesthetic6plus-min512-data/{00000..01210}.tar
```

**Comment by luosiallen** [comment]
This is inaccessible data. We provide a example for reference. For training, you need to use your private data.

**Comment by TonyLianLong** [comment]
Thank you for clarifying. I also observe that it only uses very few samples (12k) in LoRA training (with `--max_train_steps=1000` in [the example](https://github.com/luosiallen/latent-consistency-model/tree/main/LCM_Training_Script/consistency_distillation)). The dataset has around 12M images, so this is a very small subset. Do you find using this small amount of data enough for the best performance (i.e., the improvement saturates with more data)?
