### ISSUE TITLE
unet_time_cond_proj_dim，no args in train_lcm_distill_sd_wds.py

### ISSUE THREAD

**Issue by yapengyu** [luosiallen/latent-consistency-model#64]
<img width="947" alt="image" src="https://github.com/luosiallen/latent-consistency-model/assets/75412865/d771061e-577b-4852-9b75-1897664162ad">

**Comment by yapengyu** [comment]
AttributeError: 'Namespace' object has no attribute 'unet_time_cond_proj_dim'

**Comment by Crimson-pro** [comment]
```
parser.add_argument(
        "--unet_time_cond_proj_dim",
        type=int,
        default=256,
        help=(
            "The dimension of the guidance scale embedding in the U-Net, which will be used if the teacher U-Net"
            " does not have `time_cond_proj_dim` set."
        )
```
I found this new args in latest diffusers repo

**Comment by yapengyu** [comment]
@Crimson-pro Oh, greatly thx, I'll use the diffusers version
