### ISSUE TITLE
img2img

### ISSUE THREAD

**Issue by nagolinc** [luosiallen/latent-consistency-model#8]
Is there a img2img pipeline for this model?

I took a stab at it, but it only works with strength=1.0

https://gist.github.com/nagolinc/6e0d3960a81714d13b821e3694d673d6

**Comment by nagolinc** [comment]
Okay, this works a bit better

https://gist.github.com/nagolinc/53c395d8cd70a852b03fca4eb273923f

**Comment by taabata** [comment]
> Okay, this works a bit better
> 
> https://gist.github.com/nagolinc/53c395d8cd70a852b03fca4eb273923f

Thanks. That works well.

**Comment by luosiallen** [comment]
Can anyone raise a pull request under this repo officially so that we can merge it?

**Comment by nagolinc** [comment]
Okay, if anyone wants to test out the PR it is here:

https://github.com/huggingface/diffusers/pull/5477

**Comment by luosiallen** [comment]
Thank you @nagolinc ! I will ask the team to test it.

**Comment by Holmes2002** [comment]
@nagolinc Hi, how to train img2img with LCM, can you help me ?
