### ISSUE TITLE
some questions and suggestions

### ISSUE THREAD

**Issue by Amin456789** [luosiallen/latent-consistency-model#9]
Hi!
omg, only 1-4 steps???? this is greaaat!

1. i saw the dreamshaper model is about 3.4 gb, can we have fp16 models in the future too for smaller sizes?
2. PLEASE add AnimateDiff, with only 4 steps for cpu it will be a blessing for us!
3. any plans for img2img, inpainting? or if someday lcm sampler merged with automatic1111, will we be able to use dreamshaper with animatediff and img2img normally? [it will be great if u guys support cpu officially in a1111]

i found @rupeshs repo for cpu's gui, can't wait for new features!
https://github.com/rupeshs/fastsdcpu

kind regards

**Comment by Amin456789** [comment]
@JohnClaw look at this bro!

**Comment by JohnClaw** [comment]
> look at this bro!

Thanks for informing me. As far as i know Latent consistency model runs only on GPU. And my laptop has no GPU. However FastSdCpu by rupeshs looks great.

**Comment by Amin456789** [comment]
not yet, but i tested the online version and it makes pretty good with 2-3 steps too!

**Comment by luosiallen** [comment]
Img2Img is on the way. Should be add in diffusers soon. @Amin456789

**Comment by Amin456789** [comment]
thank u!
