### ISSUE TITLE
Why is CFG applied after the scheduler and not before, like in regular diffusion sampling?

### ISSUE THREAD

**Issue by qchuG** [luosiallen/latent-consistency-model#91]
We see that during training, [CFG is applied *after* the scheduler](https://github.com/luosiallen/latent-consistency-model/blob/main/LCM_Training_Script/consistency_distillation/train_lcm_distill_sd_wds.py#L1206-L1209). In regular diffusion sampling, [CFG is applied *before* the scheduler](https://github.com/huggingface/diffusers/blob/3cf4f9c7353b3d42c6b6b527df5c0359600bb197/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L1065-L1070)

What is the reason for this and is there a difference in performance?

**Comment by zjysteven** [comment]
Not sure if I misinterpret anything, but isn't the implementation you are quoting here doing "CFG *before* the scheduler"?
https://github.com/luosiallen/latent-consistency-model/blob/a9ad79587cc8bd1e404ccd1a3056a3da969b2f62/LCM_Training_Script/consistency_distillation/train_lcm_distill_sd_wds.py#L1206-L1209

**Comment by qchuG** [comment]
You're right, closing.
